# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: rootco.de
email: rbrown@opensuse.org
description: > # this means to ignore newlines until "baseurl:"
  Ramblings of a Geek, mostly about Linux, openSUSE, SUSE, and openQA.
  This site is my personal blog. The opinions expressed here represent my own and not those of my employer.
  Copyright (c) 2016 Richard Brown
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rootco.de" # the base hostname & protocol for your site
twitter_username: sysrich
github_username:  sysrich

# Build settings
markdown: kramdown
